# Karpenter Helm Values
# Generated automatically from Terraform outputs

serviceAccount:
  name: karpenter

settings:
  clusterName: kbr-proxy-eks-us-west-1-kolya
  clusterEndpoint: https://A93F58E73F646624F5B5AFE3285DFEDE.gr7.us-west-1.eks.amazonaws.com
  interruptionQueue: kbr-proxy-kolya-karpenter
