# Karpenter Helm Values
# Generated automatically from Terraform outputs

serviceAccount:
  name: karpenter

settings:
  clusterName: kbr-proxy-eks-us-west-1-kolya
  clusterEndpoint: https://1F61DF777DFA9E0AFC9C2E679AA87587.sk1.us-west-1.eks.amazonaws.com
  interruptionQueue: kbr-proxy-kolya-karpenter
