#!/bin/bash
#
# Generate Ingress YAML files from Kubernetes secret (synced by External Secrets Operator)
#
# This script reads ACM certificate ARNs and other config from the k8s secret
# 'backend-secrets' in namespace 'kbp', which is populated by ESO from AWS Secrets Manager.
#
# Usage:
#   ./generate-ingress.sh
#
# Prerequisites:
#   - kubectl configured with cluster access
#   - External Secrets Operator has synced backend-secrets in namespace kbp

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

NAMESPACE="kbp"
SECRET_NAME="backend-secrets"  # pragma: allowlist secret

# Check if kubectl can access the secret
echo "Reading configuration from k8s secret '$SECRET_NAME' in namespace '$NAMESPACE'..."
if ! kubectl get secret "$SECRET_NAME" -n "$NAMESPACE" &> /dev/null; then
    echo "❌ Error: secret '$SECRET_NAME' not found in namespace '$NAMESPACE'"
    echo "   Ensure External Secrets Operator has synced the secret from AWS Secrets Manager"
    echo "   Check: kubectl get externalsecret -n $NAMESPACE"
    exit 1
fi

# Extract values from k8s secret
FRONTEND_ACM_CERT=$(kubectl get secret "$SECRET_NAME" -n "$NAMESPACE" -o jsonpath='{.data.acm-certificate-frontend-arn}' | base64 -d)
API_ACM_CERT=$(kubectl get secret "$SECRET_NAME" -n "$NAMESPACE" -o jsonpath='{.data.acm-certificate-api-arn}' | base64 -d)
AWS_ACCOUNT_ID=$(kubectl get secret "$SECRET_NAME" -n "$NAMESPACE" -o jsonpath='{.data.aws-account-id}' | base64 -d)
AWS_REGION=$(kubectl get secret "$SECRET_NAME" -n "$NAMESPACE" -o jsonpath='{.data.aws-region}' | base64 -d)

# 从 Terraform workspace 推导环境：prod workspace = prod，其他一律 non-prod
TERRAFORM_DIR="$SCRIPT_DIR/../../iac"
if [[ -d "$TERRAFORM_DIR" ]]; then
    TF_WORKSPACE=$(cd "$TERRAFORM_DIR" && terraform workspace show 2>/dev/null || echo "default")
    if [[ "$TF_WORKSPACE" == "prod" ]]; then
        ENVIRONMENT="prod"
    else
        ENVIRONMENT="non-prod"
    fi
else
    ENVIRONMENT="non-prod"
fi

# Validate required values
if [[ -z "$FRONTEND_ACM_CERT" ]]; then
    echo "❌ Error: acm-certificate-frontend-arn not found in secret '$SECRET_NAME'"
    exit 1
fi

if [[ -z "$API_ACM_CERT" ]]; then
    echo "❌ Error: acm-certificate-api-arn not found in secret '$SECRET_NAME'"
    exit 1
fi

# Validate certificate ARN region matches deployment region
if [[ -n "$AWS_REGION" && "$FRONTEND_ACM_CERT" != *":acm:${AWS_REGION}:"* ]]; then
    echo "⚠️  Warning: Frontend certificate ARN region does not match deployment region ($AWS_REGION)"
    echo "   Certificate: $FRONTEND_ACM_CERT"
fi

if [[ -n "$AWS_REGION" && "$API_ACM_CERT" != *":acm:${AWS_REGION}:"* ]]; then
    echo "⚠️  Warning: API certificate ARN region does not match deployment region ($AWS_REGION)"
    echo "   Certificate: $API_ACM_CERT"
fi

# Read domain names from configmaps (generated by config wizard)
FRONTEND_DOMAIN=$(kubectl get configmap frontend-config -n "$NAMESPACE" -o jsonpath='{.data.VITE_MICROSOFT_REDIRECT_URI}' 2>/dev/null | sed 's|https://||;s|/auth/microsoft/callback||')
API_DOMAIN=$(kubectl get configmap backend-config -n "$NAMESPACE" -o jsonpath='{.data.KBR_ALLOWED_ORIGINS}' 2>/dev/null | sed 's|.*,https://||;s|:[0-9]*$||')

if [[ -z "$FRONTEND_DOMAIN" || -z "$API_DOMAIN" ]]; then
    echo "❌ Error: Could not read domain names from configmaps in namespace '$NAMESPACE'"
    echo "   Ensure backend-config and frontend-config ConfigMaps exist"
    exit 1
fi

echo "✅ Configuration loaded:"
echo "   AWS Account ID: $AWS_ACCOUNT_ID"
echo "   AWS Region: $AWS_REGION"
echo "   Frontend Domain: $FRONTEND_DOMAIN"
echo "   API Domain: $API_DOMAIN"
echo "   Frontend ACM Cert: ${FRONTEND_ACM_CERT:0:50}..."
echo "   API ACM Cert: ${API_ACM_CERT:0:50}..."
echo ""

# Export variables for envsubst
export FRONTEND_ACM_CERT API_ACM_CERT ENVIRONMENT FRONTEND_DOMAIN API_DOMAIN

# Generate ingress-frontend.yaml from template
echo "🔨 Generating ingress-frontend.yaml..."
envsubst < ingress-frontend.yaml.template > ingress-frontend.yaml

# Generate ingress-api.yaml from template
echo "🔨 Generating ingress-api.yaml..."
envsubst < ingress-api.yaml.template > ingress-api.yaml

echo "✅ Ingress files generated successfully!"
echo ""
echo "Next steps:"
echo "  1. Review the generated files: ingress-frontend.yaml, ingress-api.yaml"
echo "  2. Apply to cluster: kubectl apply -f ingress-frontend.yaml -f ingress-api.yaml"
echo ""
